### PR TITLE
added causes to 0x223 mismatch code

### PR DESCRIPTION
**Pull request by jonititan**
Just trying to provide clarity on initialisation failure cause

### CODE REVIEW

**Comment by it0uchpods** [comment]
Will be doing the same fix, with more user friendliness in the next version of ACCONFIG (1.4.6)

Kind Regards,
Josh

**Comment by jonititan** [comment]
Is there any chance you could add a close option to your error message dialog?
As it is if there is any irregularity on startup at all I get a 0x223 mismatch code (which doesn't tell me what failed) and then I can't close the dialog to make it go away.

**Comment by it0uchpods** [comment]
Hi Joni
As annoying as it may seem, its designed this way to prevent system failure. If a mismatch occurs, it means an important item failed to either load, or be configured correctly. The reasons will be added today. It your sim is setup correctly, you shouldn't ever see the mismatch.

Sorry about that, but its designed to prevent flight if a failure occurs.

Kind Regards,
Josh

**Comment by jonititan** [comment]
What is the design philosophy behind preventing the user from using the model as opposed to warning them it has an issue and then allowing them to ignore it?

This isn't a safety critical system and it isn't as if this is enhancing the user experience in any way.

**Comment by it0uchpods** [comment]
Hi Joni
The reason is because the Airbus flight computers do not initialize when the airplane is in the air, the aircraft gets power when the aircraft is on the ground, therefore, the systems do not initialize properly, and the aircraft will not transition to the FLIGHT phase from the GROUND phase properly.

By V1.0, I will have a condition which will automatically run the JSBsim quickstart and configure the systems of the airplane to correctly work while the aircraft is started in the air.

The mismatch prevents the user from flying the aircraft, because there will be strange and improper behavior. I do not want any excess bug reports due to misuse of the aircraft.

Hope you understand.

Kind Regards,
Josh

**Comment by jonititan** [comment]
Hi Josh,

I look forward to seeing your improvements in V1.0 but until then it looks like I need to disable a lot of the internals in order to make this usable which is quite sad.

Joni

**Comment by it0uchpods** [comment]
Hi Joni
If you can detail further what you will be using it for, I can try to find a solution soon, or implement an override, or something like that. 

Kind Regards,
Josh

**Comment by jonititan** [comment]
Hi Josh,

I will be feeding real engine data into the simulation so we can assess the ability of pilots flying a simulated mission to detect engine fluctuations shown in the Upper & Lower ECAM panels.

A number of pre-existing code examples for UDP make your aircraft lock up on startup due to these internal checks unfortunately.  I had anticipated starting two instances one with no fdm and then piping the native protocol fdm data from one to the other, modifying the engine data on the way.  However this approach encounters the mentioned problem so I am exploring alternatives while hoping I don't have to modify things too much.

As part of this work I am making webpanels for the PFD and the two ECAM panels which I will be happy to offer back to your project for your consideration regarding inclusion.

Kind regards

Joni

**Comment by it0uchpods** [comment]
Hi Joni
Ahh, that sounds very nice. Yes, that would conflict with how this model is designed, however, if you want, I can make a aircraft -set  which simply loads the Upper and Lower ECAMs.

Yes, sure, that would be great!

Kind Regards,
Josh

**Comment by jonititan** [comment]
If you could that would be very kind!

**Pull request closed without merging**
